services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v3.8.0 # 
    container_name: mealie
    restart: always
    ports:
        - "9925:9000" # 
    deploy:
      resources:
        limits:
          memory: 1000M # 
    volumes:
      - mealie-data:/app/data/
    env_file:
      - .env
    environment:
      # Set Backend ENV Variables Here
      ALLOW_SIGNUP: "false"
      PUID: 911
      PGID: 911
      TZ: EST
      BASE_URL: http://localhost:8080
      OPENAI_API_KEY: ${OPENAI_API_KEY}

volumes:
  mealie-data:
