services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: 'America/New_York'
      WEBPASSWORD: 'changeme'  # Change this password!
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    dns:
      - 1.1.1.1
      - 8.8.8.8
    cap_add:
      - NET_ADMIN
